
- name: Download Rstudio
  shell: >
    wget https://download1.rstudio.org/rstudio-{{version}}.deb
    chdir={{source_dir}} 
    creates=rstudio-{{version}}.deb

- name: Install RStudio
  shell: gdebi -n {{source_dir}}/rstudio-{{version}}.deb
